---
abstract: 'Typographic ligature filter for TT'
author:
  - 'Nick Patch <patch@cpan.org>'
build_requires:
  Test::More: 0.41
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Ligature
provides:
  Template::Plugin::Ligature:
    file: lib/Template/Plugin/Ligature.pm
    version: 0.01
requires:
  Template: 2.07
  Text::Ligature: 0
  parent: 0
  perl: v5.6.0
resources:
  bugtracker: https://github.com/patch/template-plugin-ligature-pm5/issues
  homepage: https://github.com/patch/template-plugin-ligature-pm5
  license: http://dev.perl.org/licenses/
  repository: git://github.com/patch/template-plugin-ligature-pm5.git
version: 0.01
